# Generated by Django 3.2 on 2021-04-18 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Name',
            new_name='Register',
        ),
    ]
