# Generated by Django 3.2 on 2021-04-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfi', '0002_auto_20210420_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfi',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
